config/routes.rb
UberApp::Application.routes.draw do

  get '/' => redirect("remind_cabs/remind_me")

  
  require 'sidekiq/web'
  
  if Rails.env == 'production'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  else
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :remind_cabs do
    collection do
      get 'remind_me'
    end
  end  

end

app/models/api_log.rb
class ApiLog < ActiveRecord::Base

	def self.create_logs(args)
		ApiLog.create(args)
	end	

	def self.all_logs
		ApiLog.all.order("id DESC").map(&:logs)
	end	

end	

app/models/user_information.rb
class UserInformation < ActiveRecord::Base

	validates :source_lat,:source_lng, :des_lng, :des_lng, :email, :time_to_reach, presence: true


  #schedule_job
  #author: job
	def schedule_job
    #check wheather we can remind user or not 
    #condition check if we have no time to remind user
    if self.time_to_reach - Time.zone.now <= 0.hours || (self.time_to_reach - Time.zone.now)<= self.kms.minutes
       
      #shoot email saying its too late to book an uber
      #send email
      details = {"email"=> self.email}
      CommunicationWorker.perform_async("sorry",details)
      self.email_sent = 1
      self.save
    
    #worst case
    #we take max diviation of 60 mintues + 20.minutes cab time. if condition return true we start ping before 2 hours ~ 1hour
    #this will save number of ping
		elsif ((self.time_to_reach - (self.kms.minutes + APP_CONFIG['max_diviation'].minutes)) - Time.zone.now) > APP_CONFIG['uber_cap_time'].minutes
       
      job_to_be_perform_at = (self.time_to_reach-(self.kms.minutes+APP_CONFIG['max_diviation'].minutes+APP_CONFIG['uber_cap_time'].minutes))
       # schedule job at (self.time_to_reach - (self.kms.minutes + 60.minutes)
      ApiLog.create_logs({:logs=>"Next Hit Schedule at #{job_to_be_perform_at.strftime("%d/%m/%Y @ %I:%M%P")} #{self.email}"})  
      OneTimeJob.perform_at(job_to_be_perform_at, self.id)

    else
      #schedule job which will ping google and uber to get acurate results
      IntervalJob.perform_at(0.minutes.from_now, self.id)

		end	
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/remind_cabs_controller.rb
class RemindCabsController < ApplicationController

	def remind_me
		@user_data = UserInformation.new
	end

	#save user info and get google time to reach des without traffic and schedule the job

  #author: saurav
  
  def create

		@user_data = UserInformation.new(user_params)
		duration = GoogleApi.get_time_to_travel(user_params[:source_lat], user_params[:source_lng], user_params[:des_lat], user_params[:des_lng], user_params[:email], true)
    @user_data.kms = duration
    respond_to do |format|
      if duration != -1 and @user_data.save
      	@user_data.schedule_job
        format.html { redirect_to '/remind_cabs/remind_me', notice: 'We will remind you to book an uber through an email' }
        format.json { render action: 'show', status: :created, location: @user_data}
      else
        format.html { render action: 'remind_me' } if duration!=-1
        format.html { redirect_to '/remind_cabs/remind_me', notice: 'Sorry lat or lng not valid' } if duration==-1
        format.json { render json: @user_data.errors, status: :unprocessable_entity }
      end
    end
	end

	private

	def user_params
    user_params = params.require(:user_information).permit!()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def formatDate(date)
    # date.strftime("dd/mm/yy".gsub('dd','%d').gsub('mm', '%m').gsub('yy', '%y')) if date.present? 
    date.strftime("%d/%m/%Y") if date.present?
  end

  def formatDateSlim(date)
    # date.strftime("dd/mm/yy".gsub('dd','%d').gsub('mm', '%m').gsub('yy', '%y')) if date.present? 
    date.strftime("%d/%m/%y") if date.present?
  end

  def formatTime(time)
    time.strftime("%H:%M %p") if time.present?
  end

  def formatDateTime(date, format=false)
    if date.present?
      if format
        date.strftime(format)
      else
        date.strftime("%d/%m/%Y @ %I:%M%P")
      end
    end
  end
end

app/views/layouts/application.html.haml
%html
  %head
    %title UberApp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  .container.grayBack.col-sm-12
    .row
      .height50
    - if flash[:notice]
      .alert.alert-warning.marginTop20
        %a.close{"data-dismiss" => "alert"} x
        = flash[:notice]
    - if flash[:success]
      .alert.alert-success.marginTop20
        %a.close{"data-dismiss" => "alert"} x
        = flash[:success]
    - if flash[:error]
      .alert.alert-danger.marginTop20
        %a.close{"data-dismiss" => "alert"} x
        = flash[:error]
    = yield

app/views/remind_cabs/remind_me.html.haml
.row.margin10
.row.background
  %h2.col-sm-12.text-center
    Remind me When to book an Uber
.well.whiteBack
  = form_for @user_data, url: remind_cabs_path, html: {class: 'form-horizontal'} do |f|
    - if @user_data.errors.any?
      #error_explanation
        %h4= "#{pluralize(@user_data.errors.count, "error")} prohibited this data from being saved:"
        %ul
          - @user_data.errors.full_messages.each do |msg|
            %li= msg

    .row
      .col-md-6
        .form-group
          = f.label :source_lat, class: 'control-label col-md-2'
          .col-md-10
            = f.text_field :source_lat, class: 'form-control'
      .col-md-6
        .form-group
          = f.label :source_lng, class: 'control-label col-md-2'
          .col-md-10
            = f.text_field :source_lng, class: 'form-control'
    .row
      .col-md-6
        .form-group
          = f.label :destination_lat, class: 'control-label col-md-2'
          .col-md-10
            = f.text_field :des_lat, class: 'form-control'
      .col-md-6
        .form-group
          = f.label :destination_lng, class: 'control-label col-md-2'
          .col-md-10
            = f.text_field :des_lng, class: 'form-control'

    .row{ :style=> "position: relative"}
      .col-md-6
        .form-group
          = f.label :Reach_Time, class: 'control-label col-md-2' , style: "position: relative"
          .col-md-10
            = f.text_field :time_to_reach, class: 'form-control' , id: 'datetimepicker1'
      .col-md-6  
        .form-group
          = f.label :email, class: 'control-label col-md-2'
          .col-md-10
            = f.text_field :email, class: 'form-control'                      
    .row
      .col-md-12.text-center
        = submit_tag "Remind me", :class=> 'btn btn-primary'
 
.table-responsive.div-table-content  
  %table.table-condensed.table-bordered  
    %thead
      %th Logs

    %tbody.pointerCursor
      - ApiLog.all_logs.each do |log|
        %tr
          %td= log       